/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'startTime' : Time,
  'status' : AppointmentStatus,
  'patient' : Principal,
  'doctor' : Principal,
  'endTime' : Time,
  'description' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BookingRequest {
  'startTime' : Time,
  'patient' : Principal,
  'doctor' : Principal,
  'endTime' : Time,
  'description' : string,
}
export interface DailyAvailability {
  'startTime' : Time,
  'endTime' : Time,
  'dayOfWeek' : bigint,
}
export interface DoctorAvailability {
  'doctor' : Principal,
  'createdAt' : Time,
  'weeklyAvailability' : WeeklyAvailability,
  'updatedAt' : Time,
}
export interface DoctorProfile {
  'verified' : boolean,
  'name' : string,
  'user' : Principal,
  'specialty' : string,
}
export interface MedicalFacility {
  'id' : bigint,
  'name' : string,
  'facilityType' : string,
  'distance' : number,
  'address' : string,
  'phone' : string,
  'coordinates' : [number, number],
}
export interface PatientRecord {
  'symptoms' : Array<Symptom>,
  'vitals' : Array<VitalSigns>,
}
export interface Symptom {
  'description' : string,
  'timestamp' : Time,
  'severity' : bigint,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'medicalRole' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VitalSigns {
  'temperature' : number,
  'bloodPressure' : string,
  'oxygenSaturation' : bigint,
  'heartRate' : bigint,
  'timestamp' : Time,
}
export interface WeeklyAvailability {
  'tuesday' : [] | [DailyAvailability],
  'wednesday' : [] | [DailyAvailability],
  'saturday' : [] | [DailyAvailability],
  'thursday' : [] | [DailyAvailability],
  'sunday' : [] | [DailyAvailability],
  'friday' : [] | [DailyAvailability],
  'monday' : [] | [DailyAvailability],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMedicalFacility' : ActorMethod<[MedicalFacility], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[BookingRequest], bigint>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctorAvailability' : ActorMethod<[Principal], [] | [DoctorAvailability]>,
  'getDoctorProfile' : ActorMethod<[Principal], DoctorProfile>,
  'getMedicalFacilities' : ActorMethod<[], Array<MedicalFacility>>,
  'getNearbyFacilities' : ActorMethod<
    [number, number, number],
    Array<MedicalFacility>
  >,
  'getPatientRecords' : ActorMethod<[], [] | [PatientRecord]>,
  'getPatientRecordsByUser' : ActorMethod<[Principal], [] | [PatientRecord]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'logSymptom' : ActorMethod<[Symptom], undefined>,
  'logVitals' : ActorMethod<[VitalSigns], undefined>,
  'registerDoctor' : ActorMethod<[string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setDoctorAvailability' : ActorMethod<[WeeklyAvailability], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
  'verifyDoctor' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];