/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MedicalFacility = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'facilityType' : IDL.Text,
  'distance' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingRequest = IDL.Record({
  'startTime' : Time,
  'patient' : IDL.Principal,
  'doctor' : IDL.Principal,
  'endTime' : Time,
  'description' : IDL.Text,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : AppointmentStatus,
  'patient' : IDL.Principal,
  'doctor' : IDL.Principal,
  'endTime' : Time,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'medicalRole' : IDL.Text,
});
export const DailyAvailability = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
  'dayOfWeek' : IDL.Nat,
});
export const WeeklyAvailability = IDL.Record({
  'tuesday' : IDL.Opt(DailyAvailability),
  'wednesday' : IDL.Opt(DailyAvailability),
  'saturday' : IDL.Opt(DailyAvailability),
  'thursday' : IDL.Opt(DailyAvailability),
  'sunday' : IDL.Opt(DailyAvailability),
  'friday' : IDL.Opt(DailyAvailability),
  'monday' : IDL.Opt(DailyAvailability),
});
export const DoctorAvailability = IDL.Record({
  'doctor' : IDL.Principal,
  'createdAt' : Time,
  'weeklyAvailability' : WeeklyAvailability,
  'updatedAt' : Time,
});
export const DoctorProfile = IDL.Record({
  'verified' : IDL.Bool,
  'name' : IDL.Text,
  'user' : IDL.Principal,
  'specialty' : IDL.Text,
});
export const Symptom = IDL.Record({
  'description' : IDL.Text,
  'timestamp' : Time,
  'severity' : IDL.Nat,
});
export const VitalSigns = IDL.Record({
  'temperature' : IDL.Float64,
  'bloodPressure' : IDL.Text,
  'oxygenSaturation' : IDL.Nat,
  'heartRate' : IDL.Nat,
  'timestamp' : Time,
});
export const PatientRecord = IDL.Record({
  'symptoms' : IDL.Vec(Symptom),
  'vitals' : IDL.Vec(VitalSigns),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedicalFacility' : IDL.Func([MedicalFacility], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([BookingRequest], [IDL.Nat], []),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctorAvailability' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DoctorAvailability)],
      ['query'],
    ),
  'getDoctorProfile' : IDL.Func([IDL.Principal], [DoctorProfile], ['query']),
  'getMedicalFacilities' : IDL.Func([], [IDL.Vec(MedicalFacility)], ['query']),
  'getNearbyFacilities' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(MedicalFacility)],
      ['query'],
    ),
  'getPatientRecords' : IDL.Func([], [IDL.Opt(PatientRecord)], ['query']),
  'getPatientRecordsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PatientRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'logSymptom' : IDL.Func([Symptom], [], []),
  'logVitals' : IDL.Func([VitalSigns], [], []),
  'registerDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setDoctorAvailability' : IDL.Func([WeeklyAvailability], [], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  'verifyDoctor' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MedicalFacility = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'facilityType' : IDL.Text,
    'distance' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingRequest = IDL.Record({
    'startTime' : Time,
    'patient' : IDL.Principal,
    'doctor' : IDL.Principal,
    'endTime' : Time,
    'description' : IDL.Text,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : AppointmentStatus,
    'patient' : IDL.Principal,
    'doctor' : IDL.Principal,
    'endTime' : Time,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'medicalRole' : IDL.Text,
  });
  const DailyAvailability = IDL.Record({
    'startTime' : Time,
    'endTime' : Time,
    'dayOfWeek' : IDL.Nat,
  });
  const WeeklyAvailability = IDL.Record({
    'tuesday' : IDL.Opt(DailyAvailability),
    'wednesday' : IDL.Opt(DailyAvailability),
    'saturday' : IDL.Opt(DailyAvailability),
    'thursday' : IDL.Opt(DailyAvailability),
    'sunday' : IDL.Opt(DailyAvailability),
    'friday' : IDL.Opt(DailyAvailability),
    'monday' : IDL.Opt(DailyAvailability),
  });
  const DoctorAvailability = IDL.Record({
    'doctor' : IDL.Principal,
    'createdAt' : Time,
    'weeklyAvailability' : WeeklyAvailability,
    'updatedAt' : Time,
  });
  const DoctorProfile = IDL.Record({
    'verified' : IDL.Bool,
    'name' : IDL.Text,
    'user' : IDL.Principal,
    'specialty' : IDL.Text,
  });
  const Symptom = IDL.Record({
    'description' : IDL.Text,
    'timestamp' : Time,
    'severity' : IDL.Nat,
  });
  const VitalSigns = IDL.Record({
    'temperature' : IDL.Float64,
    'bloodPressure' : IDL.Text,
    'oxygenSaturation' : IDL.Nat,
    'heartRate' : IDL.Nat,
    'timestamp' : Time,
  });
  const PatientRecord = IDL.Record({
    'symptoms' : IDL.Vec(Symptom),
    'vitals' : IDL.Vec(VitalSigns),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedicalFacility' : IDL.Func([MedicalFacility], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([BookingRequest], [IDL.Nat], []),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctorAvailability' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DoctorAvailability)],
        ['query'],
      ),
    'getDoctorProfile' : IDL.Func([IDL.Principal], [DoctorProfile], ['query']),
    'getMedicalFacilities' : IDL.Func(
        [],
        [IDL.Vec(MedicalFacility)],
        ['query'],
      ),
    'getNearbyFacilities' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(MedicalFacility)],
        ['query'],
      ),
    'getPatientRecords' : IDL.Func([], [IDL.Opt(PatientRecord)], ['query']),
    'getPatientRecordsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PatientRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'logSymptom' : IDL.Func([Symptom], [], []),
    'logVitals' : IDL.Func([VitalSigns], [], []),
    'registerDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setDoctorAvailability' : IDL.Func([WeeklyAvailability], [], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
    'verifyDoctor' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };