/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DailyAvailability {
    startTime: Time;
    endTime: Time;
    dayOfWeek: bigint;
}
export interface AuditLog {
    action: string;
    metadata?: string;
    performedBy: Principal;
    timestamp: bigint;
    targetUser?: Principal;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DoctorProfile {
    verified: boolean;
    name: string;
    user: Principal;
    specialty: string;
}
export interface BookingRequest {
    startTime: Time;
    patient: Principal;
    doctor: Principal;
    endTime: Time;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AdminInfo {
    expiresAt?: bigint;
    name: string;
    role: UserRole;
    user: Principal;
}
export interface Device {
    status: Variant_active_inactive;
    deviceId: string;
    lastSync: bigint;
    linkedPatientId?: Principal;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface PatientRecord {
    symptoms: Array<Symptom>;
    vitals: Array<VitalSigns>;
}
export interface RoleInfo {
    expiresAt?: bigint;
    isExpired: boolean;
    role: UserRole;
}
export interface WeeklyAvailability {
    tuesday?: DailyAvailability;
    wednesday?: DailyAvailability;
    saturday?: DailyAvailability;
    thursday?: DailyAvailability;
    sunday?: DailyAvailability;
    friday?: DailyAvailability;
    monday?: DailyAvailability;
}
export interface MedicalFacility {
    id: bigint;
    name: string;
    facilityType: string;
    distance: number;
    address: string;
    phone: string;
    coordinates: [number, number];
}
export interface DoctorAvailability {
    doctor: Principal;
    createdAt: Time;
    weeklyAvailability: WeeklyAvailability;
    updatedAt: Time;
}
export interface VitalSigns {
    temperature: number;
    bloodPressure: string;
    oxygenSaturation: bigint;
    heartRate: bigint;
    timestamp: Time;
}
export interface Appointment {
    id: bigint;
    startTime: Time;
    status: AppointmentStatus;
    patient: Principal;
    doctor: Principal;
    endTime: Time;
    description: string;
}
export interface Symptom {
    description: string;
    timestamp: Time;
    severity: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    status: string;
    name: string;
    role: string;
    roleExpiresAt?: bigint;
    medicalRole: string;
    previousRole?: UserRole;
    systemRole: UserRole;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    patient = "patient",
    admin = "admin",
    doctor = "doctor",
    superAdmin = "superAdmin"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_inactive {
    active = "active",
    inactive = "inactive"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMedicalFacility(facility: MedicalFacility): Promise<void>;
    addTemporaryAdmin(targetUserId: Principal, expirationTimestamp: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    bookAppointment(request: BookingRequest): Promise<bigint>;
    checkAdminExpiration(): Promise<boolean>;
    createDevice(deviceId: string): Promise<void>;
    extendAdminExpiry(targetUserId: Principal, newExpirationTimestamp: bigint): Promise<void>;
    getAllAdmins(): Promise<Array<AdminInfo>>;
    getAllDevices(): Promise<Array<Device>>;
    getAppointments(): Promise<Array<Appointment>>;
    getAuditLogs(offset: bigint, limit: bigint): Promise<Array<AuditLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDevicesByPatient(patientId: Principal): Promise<Array<Device>>;
    getDoctorAvailability(doctor: Principal): Promise<DoctorAvailability | null>;
    getDoctorProfile(doctor: Principal): Promise<DoctorProfile>;
    getMedicalFacilities(): Promise<Array<MedicalFacility>>;
    getNearbyFacilities(_latitude: number, _longitude: number, radius: number): Promise<Array<MedicalFacility>>;
    getPatientRecords(): Promise<PatientRecord | null>;
    getPatientRecordsByUser(user: Principal): Promise<PatientRecord | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(): Promise<RoleInfo>;
    isActiveAdminSession(requestingUser: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    linkDeviceToPatient(deviceId: string, patientId: Principal): Promise<void>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    logSymptom(symptom: Symptom): Promise<void>;
    logVitals(vitals: VitalSigns): Promise<void>;
    promoteToAdmin(targetUserId: Principal): Promise<void>;
    registerDoctor(name: string, specialty: string): Promise<void>;
    requestAdminAccess(): Promise<void>;
    requestApproval(): Promise<void>;
    returnToDashboard(dashboard: string): Promise<boolean>;
    revokeAdmin(targetUserId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setDoctorAvailability(weeklyAvailability: WeeklyAvailability): Promise<void>;
    toggleDeviceStatus(deviceId: string): Promise<void>;
    unlinkDevice(deviceId: string): Promise<void>;
    updateAppointmentStatus(appointmentId: bigint, newStatus: AppointmentStatus): Promise<void>;
    verifyDoctor(doctor: Principal): Promise<void>;
}
import type { AdminInfo as _AdminInfo, Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, ApprovalStatus as _ApprovalStatus, AuditLog as _AuditLog, DailyAvailability as _DailyAvailability, Device as _Device, DoctorAvailability as _DoctorAvailability, PatientRecord as _PatientRecord, RoleInfo as _RoleInfo, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, WeeklyAvailability as _WeeklyAvailability, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMedicalFacility(arg0: MedicalFacility): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicalFacility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicalFacility(arg0);
            return result;
        }
    }
    async addTemporaryAdmin(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTemporaryAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTemporaryAdmin(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: BookingRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0);
            return result;
        }
    }
    async checkAdminExpiration(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAdminExpiration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAdminExpiration();
            return result;
        }
    }
    async createDevice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDevice(arg0);
            return result;
        }
    }
    async extendAdminExpiry(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.extendAdminExpiry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extendAdminExpiry(arg0, arg1);
            return result;
        }
    }
    async getAllAdmins(): Promise<Array<AdminInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdmins();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdmins();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDevices(): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevices();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevices();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogs(arg0: bigint, arg1: bigint): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(arg0, arg1);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(arg0, arg1);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDevicesByPatient(arg0: Principal): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevicesByPatient(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevicesByPatient(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorAvailability(arg0: Principal): Promise<DoctorAvailability | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorAvailability(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorAvailability(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorProfile(arg0: Principal): Promise<DoctorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorProfile(arg0);
            return result;
        }
    }
    async getMedicalFacilities(): Promise<Array<MedicalFacility>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalFacilities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalFacilities();
            return result;
        }
    }
    async getNearbyFacilities(arg0: number, arg1: number, arg2: number): Promise<Array<MedicalFacility>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyFacilities(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyFacilities(arg0, arg1, arg2);
            return result;
        }
    }
    async getPatientRecords(): Promise<PatientRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientRecords();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientRecords();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientRecordsByUser(arg0: Principal): Promise<PatientRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientRecordsByUser(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientRecordsByUser(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(): Promise<RoleInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole();
                return from_candid_RoleInfo_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole();
            return from_candid_RoleInfo_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isActiveAdminSession(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isActiveAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isActiveAdminSession(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async linkDeviceToPatient(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkDeviceToPatient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkDeviceToPatient(arg0, arg1);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async logSymptom(arg0: Symptom): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSymptom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSymptom(arg0);
            return result;
        }
    }
    async logVitals(arg0: VitalSigns): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logVitals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logVitals(arg0);
            return result;
        }
    }
    async promoteToAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToAdmin(arg0);
            return result;
        }
    }
    async registerDoctor(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDoctor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDoctor(arg0, arg1);
            return result;
        }
    }
    async requestAdminAccess(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestAdminAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestAdminAccess();
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async returnToDashboard(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.returnToDashboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnToDashboard(arg0);
            return result;
        }
    }
    async revokeAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeAdmin(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setDoctorAvailability(arg0: WeeklyAvailability): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDoctorAvailability(to_candid_WeeklyAvailability_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDoctorAvailability(to_candid_WeeklyAvailability_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleDeviceStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDeviceStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDeviceStatus(arg0);
            return result;
        }
    }
    async unlinkDevice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlinkDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlinkDevice(arg0);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: AppointmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyDoctor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyDoctor(arg0);
            return result;
        }
    }
}
function from_candid_AdminInfo_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminInfo): AdminInfo {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLog_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLog): AuditLog {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Device_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Device): Device {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_DoctorAvailability_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoctorAvailability): DoctorAvailability {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RoleInfo_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoleInfo): RoleInfo {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklyAvailability_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyAvailability): WeeklyAvailability {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DoctorAvailability]): DoctorAvailability | null {
    return value.length === 0 ? null : from_candid_DoctorAvailability_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyAvailability]): DailyAvailability | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientRecord]): PatientRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [bigint];
    name: string;
    role: _UserRole;
    user: Principal;
}): {
    expiresAt?: bigint;
    name: string;
    role: UserRole;
    user: Principal;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.expiresAt)),
        name: value.name,
        role: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        user: value.user
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        inactive: null;
    };
    deviceId: string;
    lastSync: bigint;
    linkedPatientId: [] | [Principal];
}): {
    status: Variant_active_inactive;
    deviceId: string;
    lastSync: bigint;
    linkedPatientId?: Principal;
} {
    return {
        status: from_candid_variant_n19(_uploadFile, _downloadFile, value.status),
        deviceId: value.deviceId,
        lastSync: value.lastSync,
        linkedPatientId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.linkedPatientId))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    status: _AppointmentStatus;
    patient: Principal;
    doctor: Principal;
    endTime: _Time;
    description: string;
}): {
    id: bigint;
    startTime: Time;
    status: AppointmentStatus;
    patient: Principal;
    doctor: Principal;
    endTime: Time;
    description: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_AppointmentStatus_n24(_uploadFile, _downloadFile, value.status),
        patient: value.patient,
        doctor: value.doctor,
        endTime: value.endTime,
        description: value.description
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: string;
    metadata: [] | [string];
    performedBy: Principal;
    timestamp: bigint;
    targetUser: [] | [Principal];
}): {
    action: string;
    metadata?: string;
    performedBy: Principal;
    timestamp: bigint;
    targetUser?: Principal;
} {
    return {
        action: value.action,
        metadata: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.metadata)),
        performedBy: value.performedBy,
        timestamp: value.timestamp,
        targetUser: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.targetUser))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    name: string;
    role: string;
    roleExpiresAt: [] | [bigint];
    medicalRole: string;
    previousRole: [] | [_UserRole];
    systemRole: _UserRole;
}): {
    status: string;
    name: string;
    role: string;
    roleExpiresAt?: bigint;
    medicalRole: string;
    previousRole?: UserRole;
    systemRole: UserRole;
} {
    return {
        status: value.status,
        name: value.name,
        role: value.role,
        roleExpiresAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.roleExpiresAt)),
        medicalRole: value.medicalRole,
        previousRole: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.previousRole)),
        systemRole: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.systemRole)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doctor: Principal;
    createdAt: _Time;
    weeklyAvailability: _WeeklyAvailability;
    updatedAt: _Time;
}): {
    doctor: Principal;
    createdAt: Time;
    weeklyAvailability: WeeklyAvailability;
    updatedAt: Time;
} {
    return {
        doctor: value.doctor,
        createdAt: value.createdAt,
        weeklyAvailability: from_candid_WeeklyAvailability_n39(_uploadFile, _downloadFile, value.weeklyAvailability),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: [] | [_DailyAvailability];
    wednesday: [] | [_DailyAvailability];
    saturday: [] | [_DailyAvailability];
    thursday: [] | [_DailyAvailability];
    sunday: [] | [_DailyAvailability];
    friday: [] | [_DailyAvailability];
    monday: [] | [_DailyAvailability];
}): {
    tuesday?: DailyAvailability;
    wednesday?: DailyAvailability;
    saturday?: DailyAvailability;
    thursday?: DailyAvailability;
    sunday?: DailyAvailability;
    friday?: DailyAvailability;
    monday?: DailyAvailability;
} {
    return {
        tuesday: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.tuesday)),
        wednesday: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.wednesday)),
        saturday: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.saturday)),
        thursday: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.thursday)),
        sunday: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.sunday)),
        friday: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.friday)),
        monday: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.monday))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [bigint];
    isExpired: boolean;
    role: _UserRole;
}): {
    expiresAt?: bigint;
    isExpired: boolean;
    role: UserRole;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.expiresAt)),
        isExpired: value.isExpired,
        role: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n48(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    admin: null;
} | {
    doctor: null;
} | {
    superAdmin: null;
}): UserRole {
    return "patient" in value ? UserRole.patient : "admin" in value ? UserRole.admin : "doctor" in value ? UserRole.doctor : "superAdmin" in value ? UserRole.superAdmin : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): Variant_active_inactive {
    return "active" in value ? Variant_active_inactive.active : "inactive" in value ? Variant_active_inactive.inactive : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminInfo>): Array<AdminInfo> {
    return value.map((x)=>from_candid_AdminInfo_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Device>): Array<Device> {
    return value.map((x)=>from_candid_Device_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n46(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_WeeklyAvailability_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeeklyAvailability): _WeeklyAvailability {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    name: string;
    role: string;
    roleExpiresAt?: bigint;
    medicalRole: string;
    previousRole?: UserRole;
    systemRole: UserRole;
}): {
    status: string;
    name: string;
    role: string;
    roleExpiresAt: [] | [bigint];
    medicalRole: string;
    previousRole: [] | [_UserRole];
    systemRole: _UserRole;
} {
    return {
        status: value.status,
        name: value.name,
        role: value.role,
        roleExpiresAt: value.roleExpiresAt ? candid_some(value.roleExpiresAt) : candid_none(),
        medicalRole: value.medicalRole,
        previousRole: value.previousRole ? candid_some(to_candid_UserRole_n52(_uploadFile, _downloadFile, value.previousRole)) : candid_none(),
        systemRole: to_candid_UserRole_n52(_uploadFile, _downloadFile, value.systemRole)
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday?: DailyAvailability;
    wednesday?: DailyAvailability;
    saturday?: DailyAvailability;
    thursday?: DailyAvailability;
    sunday?: DailyAvailability;
    friday?: DailyAvailability;
    monday?: DailyAvailability;
}): {
    tuesday: [] | [_DailyAvailability];
    wednesday: [] | [_DailyAvailability];
    saturday: [] | [_DailyAvailability];
    thursday: [] | [_DailyAvailability];
    sunday: [] | [_DailyAvailability];
    friday: [] | [_DailyAvailability];
    monday: [] | [_DailyAvailability];
} {
    return {
        tuesday: value.tuesday ? candid_some(value.tuesday) : candid_none(),
        wednesday: value.wednesday ? candid_some(value.wednesday) : candid_none(),
        saturday: value.saturday ? candid_some(value.saturday) : candid_none(),
        thursday: value.thursday ? candid_some(value.thursday) : candid_none(),
        sunday: value.sunday ? candid_some(value.sunday) : candid_none(),
        friday: value.friday ? candid_some(value.friday) : candid_none(),
        monday: value.monday ? candid_some(value.monday) : candid_none()
    };
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    patient: null;
} | {
    admin: null;
} | {
    doctor: null;
} | {
    superAdmin: null;
} {
    return value == UserRole.patient ? {
        patient: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.doctor ? {
        doctor: null
    } : value == UserRole.superAdmin ? {
        superAdmin: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
